### ISSUE TITLE
easy CF mapping of variable names and units + choice what happens to unmapped vars

### ISSUE THREAD

**Issue by aurisnoctis** [DeutscherWetterdienst/mosmix2geojson#3]
### Command-line options

- [x] provide own mapping file
  `--mapfile` (implemented)

- [x] apply conversion to CF using best-effort mapping file provided and only outputting converted variables -- converting names and units, for units only scaling factors implemented for conversion
  `--map-cf` or similar (to be implemented)

- [x] optional: also output variables that don't have a mapping (yet) with MOSMIX names and units
  `--keep-unmapped` or similar

**Comment by bjoern-reetz** [comment]
The mapping functionality was reworked with v2.0.0 and now supports mapping the output to CF standard names / human readable forms out-of-box without the need for handling mapping files. You can still bring your own mapping though.

**Comment by bjoern-reetz** [comment]
One has to add that currently the CF mapping does not support all parameters. Contributions from the community are welcomed! Just take a look at the [CF mapping file](https://github.com/DeutscherWetterdienst/mosmix2geojson/blob/main/src/mosmix2geojson/cf.mapping.json) to get startet.
